config/routes.rb
Rails.application.routes.draw do
  root "owns#index"

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations' 
  }

  resources :tariffs
  get "computings/index"
  post "computings/index"
  get "computings/search", defaults: { format: :json }
  get "owns/index"
  get "owns/calcurate", defaults: { format: :json }
end

app/models/tariff.rb
class Tariff < ApplicationRecord
  belongs_to :user
  class << self

    def tariff_validating(params)
      messages = []
      empty_column = "未選択の値があります"
      empty_params = "入力データ異常"
      if params.blank?
        messages << empty_params
      else
        params.each do |k, v|
          messages << empty_column if ["", "選択してください"].include? params.values_at(k).join()
        end
      end
      messages.uniq
    end
  end
end

app/controllers/tariffs_controller.rb
class TariffsController < ApplicationController
  before_action :authenticate_user!

  def new
    @tariff = Tariff.new
  end

  def create
    messages = Tariff.tariff_validating(tariff_params)
    if messages.empty?
      Tariff.create!(tariff_params)
      redirect_to owns_index_path
    else
      p messages.join("。")
    end
  end

  private

  def tariff_params
    params.require(:tariff).permit(:name, :calc, :free, :first_from, :first_to, :first_amount, :second_from, :second_to, :second_amount, :third_from, :third_to, :third_amount, :fourth_from, :fourth_to, :fourth_amount).merge(
      user_id: current_user.id)
  end
end

app/helpers/tariffs_helper.rb
module TariffsHelper
  def symbol_to
    %i(first_to second_to third_to fourth_to)
  end

  def symbol_from
    %i(first_from second_from third_from fourth_from)
  end

  def symbol_amount
    %i(first_amount second_amount third_amount fourth_amount)
  end
end

app/views/tariffs/new.html.erb
<div class="tariff_top">よく使うタリフを保存<div>
<main>
  <div class="main_container">
  <%= form_with model: @tariff, url: tariffs_path, method: :post, local: true do |f| %>
    <label>呼び出し名：</label>
    <%= f.text_field :name, required: true %>

    <p>計算方法：<%= f.select :calc, options_for_select(calc_array) %></p>
    <p>フリータイム：<%= f.select :free, options_for_select(option_array(1)) %></p>
    <p>タリフ（以降ずっとの場合、Toの部分に999を入力し、その後の期間のFromTo両方を999にしてください）：</p>
    <% ["first", "second", "third", "fourth"].each.with_index(1) do |period, i| %>
      <p class= "period_wrap_<%= i %>">第<%= i %>期間（From から To）：<br>
      <%= f.number_field symbol_from[i-1], min:1, max: 999, class: "#{period}_from" %>
      から
      <%= f.number_field symbol_to[i-1], min:1, max: 999, class: "#{period}_to" %><br>
      金額：<%= f.select symbol_amount[i-1], options_for_select(price_array), class: "#{period}_amount" %></p>
    <% end %>
    <%= f.submit "保存する", id: "save_tariff" %>
  <% end %>
  </div>
</main>